python sandbox.py --grouping sample --sample_sizes 1 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 3 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 6 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 30 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 60 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 302 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 604 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 1208 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 1812 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 2416 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 3020 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 3624 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 4228 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 4832 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 5436 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out
python sandbox.py --grouping sample --sample_sizes 5980 --num_samples 25 --indices 1,25 --dataset ml-1m --send_to_out