python sandbox.py --grouping gender --userfrac 1.0 --ratingfrac 0.5 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping gender --userfrac 0.5 --ratingfrac 1.0 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping age --userfrac 1.0 --ratingfrac 0.5 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping age --userfrac 0.5 --ratingfrac 1.0 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping power --userfrac 1.0 --ratingfrac 0.5 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping power --userfrac 0.5 --ratingfrac 1.0 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping occupation --userfrac 1.0 --ratingfrac 0.5 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping occupation --userfrac 0.5 --ratingfrac 1.0 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping genre --userfrac 1.0 --ratingfrac 0.5 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping genre --userfrac 0.5 --ratingfrac 1.0 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping genre_strict --userfrac 1.0 --ratingfrac 0.5 --dataset ml-1m --num_samples 10 --indices 1,10
python sandbox.py --grouping genre_strict --userfrac 0.5 --ratingfrac 1.0 --dataset ml-1m --num_samples 10 --indices 1,10